name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: cargo test --verbose

    - name: Upload test results
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/debug/deps/*.d

    - name: Build (Release)
      run: cargo build --release --verbose

    - name: Upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: ax206lcd
        path: target/release/ax206lcd
